require_relative "scripts/h3_visualisation"
require_relative "scripts/playgrounds"
require "open3"

namespace :parques_infantis do
  fetch_remote_url(
    ENV.fetch("EXTRA_PLAYGROUNDS_URL", "https://docs.google.com/spreadsheets/d/e/2PACX-1vRvEr455sf7o24TvGXp3wvOuYEHUvePC6Bi6yT5yTXARtazHvZlynhxnAELa3s0CbWAYVO2SLzhy_Fy/pub?gid=0&single=true&output=csv"),
    "tmp/parques_infantis/extra_playgrounds.csv"
  )
  fetch_remote_url(
    ENV.fetch("EXTRA_QUIOSQUES_URL", "https://docs.google.com/spreadsheets/d/e/2PACX-1vRvEr455sf7o24TvGXp3wvOuYEHUvePC6Bi6yT5yTXARtazHvZlynhxnAELa3s0CbWAYVO2SLzhy_Fy/pub?gid=2084733430&single=true&output=csv"),
    "tmp/parques_infantis/extra_quiosques.csv"
  )
  file "tmp/parques_infantis/parques_infantis.geojson": [
    "tmp/parques_infantis/extra_quiosques.csv",
    "tmp/parques_infantis/extra_playgrounds.csv"
  ] do |task|
    extra_quiosques_path, extra_playgrounds_path = task.sources
    Areas::ParquesInfantis::Scripts::Playgrounds.call(task.name, extra_quiosques_path, extra_playgrounds_path)
  end

  file "tmp/parques_infantis/h3.geojson": [
    "tmp/parques_infantis/parques_infantis.geojson",
    "tmp/census_2021/BGRI2021_1106.geojson"
  ] do |task|
    parques_path, bgri2021_path = task.sources
    Areas::ParquesInfantis::Scripts::H3Visualisation.call(task.name, parques_path, bgri2021_path)
  end

  tippecanoe_file "site/assets/data/processed/parques_infantis.pmtiles": [
    "tmp/parques_infantis/parques_infantis.geojson",
    "tmp/parques_infantis/h3.geojson"
  ]

  task all: [
    "site/assets/data/processed/parques_infantis.pmtiles"
  ]

  CLEAN.include(
    "tmp/parques_infantis/extra_playgrounds.csv",
    "tmp/parques_infantis/extra_quiosques.csv",
    "site/assets/data/processed/parques_infantis.pmtiles",
    "tmp/parques_infantis/h3.geojson",
    "tmp/parques_infantis/parques_infantis.geojson"
  )
end
